name: Laravel CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  web-deploy:
    name: Deploying
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.fastrade.co.in
          username: raktim@dev.fastrade.co.in
          password: ^CyXRuOi1LvB
          server-dir: ./
      - name: Access Terminal
        run: 
          ssh apsmafkz@fastrade.co.in
      - name: Enter Password
        run: 
          Raktim@@365249
      - name: Access Dev
        run:
          cd dev.fastrade.co.in/php
      - name: Composer Install
        run:
      - name: Generate Key 
        run:
          php artisan key:generate