name: Laravel CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  web-deploy:
    name: Deploying
    runs-on: ubuntu-latest
    steps:      
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: fastrade.co.in
          username: apsmafkz
          password: Raktim@@365249
          port: 22
          script: ls
      