name: Laravel CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  web-deploy:
    name: Deploying
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1.21'
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.fastrade.co.in
          username: raktim@dev.fastrade.co.in
          password: ^CyXRuOi1LvB
          server-dir: ./

      - name: Install Dependencies
        run: composer update --ignore-platform-reqs
        working-directory: ./php

      - name: Generate key
        run: php artisan key:generate
        working-directory: ./php
      